version: '3.8'
services:
    # proxy:
    #     image: traefik
    #     volumes:
    #         - "/var/run/docker.sock:/var/run/docker.sock:ro"
    #     command:
    #         - "--api.insecure=true"
    #         - "--api.dashboard=true"
    #         - "--providers.docker=true"
    #         - "--providers.docker.exposedbydefault=false"
    #         - "--entrypoints.web.address=:80"
    #         - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
    #         - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    #         - "--entrypoints.websecure.address=:443"
    #     ports:
    #         - "443:443"
    #         - "80:80"
    #         - "8081:8080" # pour le dashboard
    #     networks:
    #         - horizon
    #     restart: unless-stopped

    database:
        image: postgres:alpine
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - ./database:/var/lib/postgresql/data
            # - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            # - ./database/backups:/backups
        networks:
            - technight
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            TZ: ${TIMEZONE} # sets time zone for the container's OS

        ports:
            - ${DB_PORT}:5432
    # backend:
    #     build:
    #         context: fastapi
    #     networks:
    #         - technight
    #     depends_on:
    #         - database
    #     env_file:
    #         - ./.env
    #     labels:
    #         traefik.enable: true
    #         traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes: /api/v1

    #         traefik.http.routers.backend.rule: PathPrefix(`/api/v1`)
    #         traefik.http.routers.backend.priority: 1
    #         traefik.http.routers.backend.service: fastapi
    #         traefik.http.routers.backend.entrypoints: websecure
    #         traefik.http.routers.backend.tls.options: default
    #         traefik.http.routers.backend.middlewares: "backend-stripprefix"
    #         traefik.http.services.fastapi.loadbalancer.server.port: 80
    # frontend:
    #     build:
    #         context: frontend
    #     volumes:
    #         - /etc/timezone:/etc/timezone:ro
    #         - /etc/localtime:/etc/localtime:ro
    #         - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    #     networks:
    #         - horizon
    #     restart: unless-stopped
    #     labels:
    #         traefik.enable: true

    #         traefik.http.routers.web.rule: PathPrefix(`/`)
    #         traefik.http.routers.web.priority: 2
    #         traefik.http.routers.web.service: nginx
    #         traefik.http.routers.web.entrypoints: websecure
    #         traefik.http.routers.web.tls.options: default
    #         traefik.http.services.nginx.loadbalancer.server.port: 80
networks:
    technight:
        name: technight
